Routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::middleware(['auth'])->group(function () {
    Route::prefix('manage')->group(function() {
        Route::prefix('jobfair')->group(function() {
            Route::prefix('master')->group(function() {

                Route::name('jobfair.')->group(function() {
                    Route::name('participant-type.')->group(function() {
                        Route::get('/participant-type', 'Admin\Master\ParticipantTypeController@index')->name('index');
                        Route::get('/participant-type/create', 'Admin\Master\ParticipantTypeController@create')->name('create');
                        Route::post('/participant-type/create', 'Admin\Master\ParticipantTypeController@store')->name('store');
                        Route::get('/participant-type/{id}/edit', 'Admin\Master\ParticipantTypeController@edit')->name('edit');
                        Route::post('/participant-type/{id}', 'Admin\Master\ParticipantTypeController@update')->name('update');
                        Route::delete('/participant-type/{id}', 'Admin\Master\ParticipantTypeController@destroy')->name('destroy');
                    });
                });
            });
            Route::get('/', 'Admin\JobFairController@index');
        });
    });
});

Entities/ParticipantType.php
<?php

namespace Modules\JobFair\Entities;

use Illuminate\Database\Eloquent\Model;
use App\Traits\Uuid as TraitsUuid;

class ParticipantType extends Model
{
    use TraitsUuid;

    protected $table = 'jf_participant_type';

    public $incrementing    = false;

    protected $casts = [
        'start_date' => 'datetime',
        'end_date' => 'datetime'
    ];

    protected $fillable = [
        'code',
        'desc',
        'amount',
        'quantity',
        'start_date',
        'end_date',
        'is_active'
    ];
    
}

Http/Controllers/Admin/JobFairController.php
<?php

namespace Modules\JobFair\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;

class JobFairController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        return view('jobfair::admin.index');
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        return view('jobfair::create');
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Response
     */
    public function show($id)
    {
        return view('jobfair::show');
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Response
     */
    public function edit($id)
    {
        return view('jobfair::edit');
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

Http/Controllers/Admin/Master/ParticipantTypeController.php
<?php

namespace Modules\JobFair\Http\Controllers\Admin\Master;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Modules\JobFair\Entities\ParticipantType;

class ParticipantTypeController extends Controller
{
    protected $pageTitle;

    public function __construct()
    {
        $this->pageTitle = 'Participant Type';
    }
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        $params['pageTitle']    = $this->pageTitle;
        $params['no']           = 1;
        $params['data']         = ParticipantType::all();
        return view('jobfair::admin.master.participant-type.index', $params);
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        $params['pageTitle']    = $this->pageTitle;
        return view('jobfair::admin.master.participant-type.create', $params);
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        try {
            $data['code']   = trim($request->code);
            $data['desc']   = trim($request->desc);
            $data['amount'] = cleanNominal($request->amount);
            $data['quantity']   = cleanNominal($request->quantity);
            $data['start_date'] = !empty($request->start_date) ? dateFormatYmd($request->start_date) : null;
            $data['end_date']   = !empty($request->end_date) ? dateFormatYmd($request->end_date) : null;
            $data['is_active']  = $request->is_active == null ? 0 : 1;

            ParticipantType::create($data);
            return redirect(route('jobfair.participant-type.index'))
				->with('success', trans('message.success_save'));
        } catch (\Exception $e) {
            return redirect(route('jobfair.participant-type.index'))
				->with('error', trans('message.error_save'));
        }
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Response
     */
    public function edit($id)
    {
        $params['pageTitle']    = $this->pageTitle;
        $params['data']         = ParticipantType::findOrFail($id);
        return view('jobfair::admin.master.participant-type.edit', $params);
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        try {
            $data['desc']   = trim($request->desc);
            $data['amount'] = cleanNominal($request->amount);
            $data['quantity']   = cleanNominal($request->quantity);
            $data['start_date'] = !empty($request->start_date) ? dateFormatYmd($request->start_date) : null;
            $data['end_date']   = !empty($request->end_date) ? dateFormatYmd($request->end_date) : null;
            $data['is_active']  = $request->is_active == null ? 0 : 1;
            ParticipantType::findOrFail($id)
                ->update($data);
            return redirect(route('jobfair.participant-type.index'))
				->with('success', trans('message.success_edit'));
        } catch (\Exception $e) {
            return redirect(route('jobfair.participant-type.index'))
				->with('error', trans('message.error_edit'));
        }
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Response
     */
    public function destroy($id)
    {
        try {
            ParticipantType::findOrFail($id)
                ->delete();
            return redirect(route('jobfair.participant-type.index'))
				->with('success', trans('message.success_delete'));
        } catch (\Exception $e) {
            return redirect(route('jobfair.participant-type.index'))
				->with('error', trans('message.error_delete'));
        }
    }
}

Resources/views/admin/index.blade.php
@extends('jobfair::admin.layouts.master')

@section('content')
    <h1>Hello World</h1>

    <p>
        This view is loaded from module: {!! config('jobfair.name') !!}
    </p>
@stop

Resources/views/admin/layouts/master.blade.php
@extends('layouts.app')

Resources/views/admin/master/participant-type/create.blade.php
@extends('jobfair::admin.layouts.master')

@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title"></h3>
                <div class="box-tools pull-right">
                    <a class="btn btn-sm btn-danger" href="{!! route('jobfair.participant-type.index') !!}">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            {!! Form::open([ 'route' => 'jobfair.participant-type.store', 'class' => 'form-horizontal', 'autocomplete' => 'off' ]) !!}
                <div class="box-body">
                    <div class="form-group">
                        <label for="code" class="col-sm-2 control-label">Code</label>
                        <div class="col-sm-3">
                            {!! Form::text('code', null, [ 'class' => 'form-control', 'required', 'autofocus']) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="desc" class="col-sm-2 control-label">Description</label>
                        <div class="col-sm-5">
                            {!! Form::textarea('desc', null, [ 'class' => 'form-control', 'required', 'rows' => 2, 'maxlength' => 200]) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="amount" class="col-sm-2 control-label">Amount</label>
                        <div class="col-sm-3">
                            {!! Form::text('amount', 0, [ 'class' => 'form-control text-right number', 'required']) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="quantity" class="col-sm-2 control-label">Quantity</label>
                        <div class="col-sm-3">
                            {!! Form::number('quantity', 1, [ 'class' => 'form-control text-right', 'required']) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="start_date" class="col-sm-2 control-label">Start Date</label>
                        <div class="col-sm-3">
                            {!! Form::text('start_date', null, [ 'class' => 'form-control datepicker']) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="end_date" class="col-sm-2 control-label">End Date</label>
                        <div class="col-sm-3">
                            {!! Form::text('end_date', null, [ 'class' => 'form-control datepicker']) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="is_active" class="col-sm-2 control-label">Active? </label>
                        <div class="col-sm-5">
                            <div class="checkbox">
                                <label>
                                    {!! Form::checkbox('is_active', true, true) !!} Yes
                                </label>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="box-footer">
                    <button type="reset" class="btn btn-default">Cancel</button>
                    <button type="submit" class="btn btn-info pull-right">Save</button>
                </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>
@endsection

@section('css')
    <style>
        .datepicker table tr td.disabled{
            color:red;
            cursor: not-allowed;
        }
        .datepicker table tr td.today{
            background: orange;
        }
        .datepicker table tr td.active{
            font-weight: bold;
        }
    </style>
@endsection

@section('scripts')
<script>
    $(document).ready(function() {
        $(".number").number(true, 0);
        $('.datepicker').datepicker({
            format: 'dd-mm-yyyy',
            autoclose: true,
            todayHighlight: true,
            weekStart: 1,
            startDate: new Date(),
            language: 'id'
        });
    });
</script>
@endsection

Resources/views/admin/master/participant-type/edit.blade.php
@extends('jobfair::admin.layouts.master')

@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title"></h3>
                <div class="box-tools pull-right">
                    <a class="btn btn-sm btn-danger" href="{!! route('jobfair.participant-type.index') !!}">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            {!! Form::open([ 'route' => ['jobfair.participant-type.update', $data->id], 'class' => 'form-horizontal', 'autocomplete' => 'off' ]) !!}
                <div class="box-body">
                    <div class="form-group">
                        <label for="code" class="col-sm-2 control-label">Code</label>
                        <div class="col-sm-3">
                            {!! Form::text('code', $data->code, [ 'class' => 'form-control', 'required', 'readonly']) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="desc" class="col-sm-2 control-label">Description</label>
                        <div class="col-sm-5">
                            {!! Form::textarea('desc', $data->desc, [ 'class' => 'form-control', 'required', 'rows' => 2, 'maxlength' => 200]) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="amount" class="col-sm-2 control-label">Amount</label>
                        <div class="col-sm-3">
                            {!! Form::text('amount', $data->amount, [ 'class' => 'form-control text-right number', 'required']) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="quantity" class="col-sm-2 control-label">Quantity</label>
                        <div class="col-sm-3">
                            {!! Form::number('quantity', $data->quantity, [ 'class' => 'form-control text-right', 'required']) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="start_date" class="col-sm-2 control-label">Start Date</label>
                        <div class="col-sm-3">
                            {!! Form::text('start_date', $data->start_date, [ 'class' => 'form-control datepicker']) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="end_date" class="col-sm-2 control-label">End Date</label>
                        <div class="col-sm-3">
                            {!! Form::text('end_date', $data->end_date, [ 'class' => 'form-control datepicker']) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="is_active" class="col-sm-2 control-label">Active? </label>
                        <div class="col-sm-5">
                            <div class="checkbox">
                                <label>
                                    {!! Form::checkbox('is_active', true, $data->is_active) !!} Yes
                                </label>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="box-footer">
                    <button type="reset" class="btn btn-default">Cancel</button>
                    <button type="submit" class="btn btn-info pull-right">Update</button>
                </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>
@endsection

@section('css')
    <style>
        .datepicker table tr td.disabled{
            color:red;
            cursor: not-allowed;
        }
        .datepicker table tr td.today{
            background: orange;
        }
        .datepicker table tr td.active{
            font-weight: bold;
        }
    </style>
@endsection

@section('scripts')
<script>
    $(document).ready(function() {
        $(".number").number(true, 0);
        $('.datepicker').datepicker({
            format: 'dd-mm-yyyy',
            autoclose: true,
            todayHighlight: true,
            weekStart: 1,
            startDate: new Date(),
            language: 'id'
        });
    });
</script>
@endsection

Resources/views/admin/master/participant-type/index.blade.php
@extends('jobfair::admin.layouts.master')

@section('content')
    
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title"></h3>
                <div class="box-tools pull-right">
                    {{-- @can('participant-type-create') --}}
                        <a class="btn btn-sm btn-success" href="{!! route('jobfair.participant-type.create') !!}">
                            <i class="fa fa-plus"></i> New Participant Type
                        </a>
                    {{-- @endcan --}}
                </div>
            </div>
            <div class="box-body" style="min-height: 520px">
                <table id="grid-participant-type" class="table table-bordered table-striped table-responsive table-condensed">
                    <thead>
                        <tr>
                            <th style="width: 5%">No.</th>
                            <th>Code</th>
                            <th>Description</th>
                            <th>Amount</th>
                            <th>Quantity</th>
                            <th>Start Date</th>
                            <th>End Date</th>
                            <th>Is Active</th>
                            <th style="width: 10%">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($data as $row)
                            <tr>
                                <td class="text-center">{!! $no++ !!}</td>
                                <td>{!! $row->code !!}</td>
                                <td>{!! $row->desc !!}</td>
                                <td class="text-right">{!! numberFormat($row->amount) !!}</td>
                                <td class="text-right">{!! $row->quantity !!}</td>
                                <td class="text-center">{!! !empty($row->start_date) ? dateFormatDmy($row->start_date) : null !!}</td>
                                <td class="text-center">{!! !empty($row->end_date) ? dateFormatDmy($row->end_date) : null !!}</td>
                                <td class="">{!! $row->is_active == true ? 'Yes' : 'No' !!}</td>
                                <td class="">
                                    @can('participant-type-edit')
                                        <a href="{!! route('jobfair.participant-type.edit', $row->id) !!}" class="btn btn-xs btn-success">Edit</a>
                                    @endcan
                                    @can('participant-type-delete')
                                        {!! Form::open(['method' => 'DELETE','route' => ['jobfair.participant-type.destroy', $row->id],'style'=>'display:inline']) !!}
                                            {!! Form::submit('Delete', ['class' => 'btn btn-xs btn-danger']) !!}
                                        {!! Form::close() !!}
                                    @endcan
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td class="text-danger text-center" colspan="6">No data found.</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@stop

Resources/views/admin/shared/sidebar.blade.php
<li class="treeview @if($adminActiveMenu == 'jobfair') active @endif">
    <a href="#">
        <i class="fa fa-globe"></i>
        <span>Job Fair</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
            <span class="label label-danger pull-right">
                New
            </span>
        </span>
    </a>
    <ul class="treeview-menu">
        <li class="@if($adminActiveSubMenu == 'master') active @endif">
            <a href="#">
                <i class="fa fa-circle-o"></i> Master
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li class="@if($urlSegment4 == 'participant-type') active @endif">
                    <a href="{!! route('jobfair.participant-type.index') !!}">
                        <i class="fa fa-circle-o"></i> Participant Type
                        <span class="pull-right-container"></span>
                    </a>
                </li>
            </ul>
        </li>
        {{-- <li class="@if($adminActiveSubMenu == 'master') active @endif">
            <a href="{!! route('shortener.url.index') !!}">
                <i class="fa fa-circle-o"></i> Master
                <span class="pull-right-container"></span>
            </a>
        </li> --}}
    </ul>
</li>